### ISSUE TITLE
Add guid property for root level log

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#483] opened 2021-01-01 22:36 UTC
A log itself has a conceptual identity as a bundle of tool runs. We should provide a `guid` property for it.

* * * *
**FINAL PROPOSAL**

**§3.13 sarifLog object
§3.13.6 guid property (proposed)**

### guid property{#sariflog-object--guid-property}

A `sarifLog` object **SHALL** contain a property named `guid` whose value is a GUID-valued string ([§3.5.3](#guid-valued-strings)) that provides a unique, stable identifier for the `sarifLog` designating that the log itself has a conceptual identity as a bundle of tool runs for tracking a SARIF log through a distributed results processing pipeline.

**Comment by schlaman-ms** [comment] 2023-08-09 21:04
### Document location for issue:
Possible new subsection under §3.13 sarifLog object
§3.13.6 id property

**Comment by stacywray** [comment] 2023-12-12 23:32
@sthagen Per @michaelcfanning, this issue is a dupe of #453, but this issue was never closed. However, this issue has the "design-approved" label and #453 does not. I will leave it up to you to decide which issue to favor. For now, I will move forward in this issue with the proposed markdown.

**Comment by stacywray** [comment] 2023-12-14 01:08
**§3.13 sarifLog object
§3.13.6 guid property (proposed)**

### guid property{#sariflog-object--guid-property}

A `sarifLog` object **SHALL** contain a property named `guid` whose value is a GUID-valued string ([sec](#guid-valued-strings)), which provides a unique, stable identifier for the `sarifLog` object designating that the log itself has a conceptual identity as a bundle of tool runs for tracking a SARIF log through a distributed results processing pipeline.

**Comment by sthagen** [comment] 2024-07-10 11:03
@KalleOlaviNiemitalo thanks for the feedback. The TC will consider softening the compliance statement, but I do not think there is any reason to re-label the change proposal (if I remember the rationale behind it correctly) - 3 1/2 years feels like a long time.

The editors will investigate the situation across other guid occurences. 
Unfortunately, in organizations that enforce strict ruling on json schema, any addition will a breaking change ...

**Comment by sthagen** [comment] 2024-07-10 11:12
Comparing the rationale part of the [initial proposal](https://github.com/oasis-tcs/sarif-spec/issues/483#issue-777364983) with the [editor version](https://github.com/oasis-tcs/sarif-spec/issues/483#issuecomment-1854939667) a SHOULD became a SHALL. I consider changing the proposed implementation in #641 to match the original rationale and of course add the forgotten schema change to the change set.

**Closed** 2024-07-26 02:15 UTC
Labels: impact-non-breaking-change, design-approved, 2.2.0, proposal
