### ISSUE TITLE
CONSIDER: Adding a triageState property to result

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#36] opened 2017-09-26 21:15 UTC
Copied from https://github.com/sarif-standard/sarif-spec/issues/279, created by @lgolding:

Some customers want to be able to put a "check mark" next to an item in a results viewer, to indicate "reviewed". Is this purely a function of a SARIF viewer, or should we add a field like `triageState` with values like `New` and `Reviewed` to persist this?

**Comment by michaelcfanning** [comment] 2017-10-11 15:06
We are tracking this issue in a master discussion item #48.

See also discussion in #12 which is a duplicate of this.

**Closed by michaelcfanning** 2017-10-11 15:06 UTC

**Comment by lgolding** [comment] 2018-01-25 01:22
Marking individual issues related to result management with the `result-management` label.
