### ISSUE TITLE
We do not have an automationGuid to match automationLogicalId

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#229] opened 2018-08-31 22:04 UTC

**Comment by lgolding** [comment] 2018-09-25 00:59
@michaelcfanning We have the property `run.correlationGuid` that is intended to hold (for example) the VSTS GUID that identifies the "build definition". Are you proposing to rename it to "automationGuid"? (If so that would be great -- I never liked "correlationGuid" for this.) Or are you saying we're still missing a concept?

**Comment by lgolding** [comment] 2018-09-27 21:43
@michaelfanning I am going to close this as duplicate of #217, "Consider adding a discrete id object," since that's where we landed in terms of addressing this.

**Closed by lgolding** 2018-09-27 21:43 UTC
Labels: CSD.2, impact-non-breaking-change, resolved-duplicate
