### ISSUE TITLE
Suggestion: platform specific data to indicate file path case sensitivity

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#209] opened 2018-07-26 16:57 UTC
Windows and *nix platforms differ here obviously. We might want to create a property to specify whether emitted file paths are case insensitive or not. This could be inferred from a general platform designator.

This relates to other issues, e.g., around new line sequence. We have to resolve the issue of defaults. We should consider rather we should be bundling all of this stuff into a single multi-member property or if we hang discrete properties off the run object.

Making these descriptors required is a difficult breaking change. There's no good set of defaults that doesn't favor one platform over another. One way to thread the needle here: allow this data to be optional and simply note that consumers must either have some understanding of the origin of their files or run a post-processor that populates the information (for a pipeline that accepts inputs from multiple platforms).

Microsoft's internal SARIF v2-driven tools pipeline has contributions from both platforms. In our system, we normalize all SARIF data before sending to the SARIF ingestion end-point, which is an opportunity to inject platform-specific properties. We could also update the SARIF-SDK (which runs on both platforms) to auto-emit these properties for any tools that use those helpers.

**Comment by michaelcfanning** [comment] 2018-11-27 18:31
@lgolding I propose to close this work item. or to mark it as impact-documentation-only to describe how we address this issue. @kupsch, also interested in your take due to the emphasis of your cross-platform work.

in brief, i think windows producers can normalize file paths to lower-case if necessary to support cross-platform scenarios. the obvious data of concern is the files table. two identical paths in this table that differ only by case are appropriate for non-windows platforms but not for windows.

the primary value of this data would be to help validators identify poorly constructed SARIF (e.g., as above, we could note conditions where the files table contains duplicated entries). is this sufficient value?

**Comment by michaelcfanning** [comment] 2018-11-27 20:04
Right. Basically, the burden is on the producer. If file paths, etc., are generated for a case-insensitive file system, there should be no constructs where file paths differ only by case.

Our validator can still help with this by either providing a single observation 'One or more file paths were observed in a common data structure that differed only by case. If this log file was produced by an analysis running on an operating system with a case-insensitive file system, that could indicate some unwanted duplication exists.' Alternately, this could be a disabled by default validation rule. Or, the validating web site could have a dropdown for analysis that is tuned for Microsoft Windows (R) or Unix (R) platforms.

**Comment by lgolding** [comment] 2018-11-27 21:49
The actual guidance can't be "pull everything to lower case". It has to be "preserve case". This is important when a project was created on Unix with mixed-case file names, and then cloned to Windows. A SARIF producer that runs on Windows must create `"uri"` values that preserve case. Otherwise, a SARIF consumer that reads the log file on Unix won't be able to find the files.

**Comment by lgolding** [comment] 2018-11-27 21:50
@michaelcfanning So having said that, this isn't an editorial change. It's a normative change because a SARIF producer at least SHOULD, and IMO SHALL, behave this way. Please comment.

**Comment by kupsch** [comment] 2018-11-27 21:56
I think that producers should preserve case, and use the same case for each file component
 as what is created in the file system.  If this were done, then it might be useful to kno
wn what parts of a file system are case-(in)sensitive, but consumers should not need it.

Both Windows and Mac OS are case-insensitive and case-preserving.  Mac OS and Linux allow a file system to be either case sensitive or insensitive, so parts of the file system can be sensitive and others not, base on the underlying mounted file system.  Either 1) producers need to specify if the file system is case-insensitive, perhaps as an attribute of the originalUriBaseIds (or better yet a generalized versionControlProvenance object), or producers need to use the same character code point sequence when referring to the same file in the file system.

If producers preserve case, they should yield the same sequences of character for the same file in the file system, but build and configuration data sometimes refers to the same file system name with two different cases and might cause tooling to emit two equivalent string for a path when case is ignored.  In working with .NET on linux, We've seen several software packages fail to build because a file is spelled "x.cs" in one place in a .csproj file and "X.cs" in another.

Since it is necessary to keep the file list and originalUriBaseIds in memory, a producer on case-insensitive file system could use the same character sequence as the first one seen for each directory component.  This could be done by a sarif generator library.  This would at least make thing consistent so consumers so consumers can just compare in a case sensitive way.  Then if an archive of the files is made and unarchived on a case-sensitive file system paths should just work (unless the case of the first path was incorrect).  If the information about what parts of the file system are case-sensitive or not were available then a consumer could locate files in all cases.

**Comment by michaelcfanning** [comment] 2019-01-24 15:12
Summary of recommendation: producers should preserve case of file/resource names. Case-sensitive platforms should prefer a single representation to identify specific entities (i.e. not refer to them with names that vary only by case). An SDK could assist with this. This discussion relates in part to the path normalization discussion elsewhere (i.e., we should prefer not to have duplicate entries in the files table due to rendering the path to them in different ways).

**Comment by michaelcfanning** [comment] 2019-01-24 21:33
SARIF producers should preserve the case of file paths as they actually exist on disk

**Comment by lgolding** [comment] 2019-03-29 16:31
@michaelcfanning @kupsch 

Please see the change draft for #315. I think it covers this and we should close this as duplicate. Even if you don't like #315 exactly as written, I don't think we need a separate item for this.

**Comment by lgolding** [comment] 2019-04-03 21:36
@michaelcfanning Agrees this is duplicate of #315.

**Closed by lgolding** 2019-04-03 21:36 UTC
Labels: design-approved, editorial, impact-documentation-only, p1, resolved-duplicate, triage-approved
